version: '3.8'
services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - 80:80
    links:
      - app
    depends_on:
      - redis
      - app
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
      secrets:
        - npmrc
    environment:
      - MEXIT_BACKEND_GOOGLE_CLIENT_ID
      - MEXIT_BACKEND_GOOGLE_CLIENT_SECRET
      - MEX_DEFAULT_USER_REFRESH_TOKEN
      - MEXIT_BACKEND_CLIENT_ID
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - MEXIT_BACKEND_REDIS_HOST=redis
      - MEXIT_BACKEND_REDIS_PORT=6379
      - REST_API_KEY

    volumes:
      - ./:/usr/src/app
    ports:
      - 5002:5002

    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    command: redis-server
    ports:
     - "6379:6379"
    volumes:
      - cache:/data

secrets:
  npmrc:
    file: $HOME/.npmrc

volumes:
  cache:
    driver: local