import NodeController from '../controllers/NodeController';
import { AuthRequest } from '../middlewares/authrequest';

export const initializeNodeRoutes = (
  nodeControllerObject: NodeController
): void => {
  nodeControllerObject._router.get(
    `${nodeControllerObject._urlPath}/archive`,
    [AuthRequest],
    nodeControllerObject.getArchivedNodes
  );
  nodeControllerObject._router.post(
    nodeControllerObject._urlPath,
    [AuthRequest],
    nodeControllerObject.createNode
  );
  nodeControllerObject._router.get(
    `${nodeControllerObject._urlPath}/linkhierarchy`,
    [AuthRequest],
    nodeControllerObject.getLinkHierarchy
  );
  nodeControllerObject._router.post(
    `${nodeControllerObject._urlPath}/:nodeId/append`,
    [AuthRequest],
    nodeControllerObject.appendNode
  );

  nodeControllerObject._router.post(
    `${nodeControllerObject._urlPath}/capture`,
    [AuthRequest],
    nodeControllerObject.newCapture
  );

  nodeControllerObject._router.post(
    `${nodeControllerObject._urlPath}/capture/link`,
    [AuthRequest],
    nodeControllerObject.createLinkCapture
  );
  nodeControllerObject._router.get(
    `${nodeControllerObject._urlPath}/getactivityblocks`,
    [AuthRequest],
    nodeControllerObject.getLastNActivityBlocks
  );
  nodeControllerObject._router.get(
    `${nodeControllerObject._urlPath}/:nodeId/`,
    [AuthRequest],
    nodeControllerObject.getNode
  );
  nodeControllerObject._router.get(
    `${nodeControllerObject._urlPath}/all/:userId`,
    [AuthRequest],
    nodeControllerObject.getAllNodes
  );
  nodeControllerObject._router.post(
    `${nodeControllerObject._urlPath}/activitynode`,
    [AuthRequest],
    nodeControllerObject.createActivityNodeForUser
  );
  nodeControllerObject._router.post(
    `${nodeControllerObject._urlPath}/block/movement`,
    [AuthRequest],
    nodeControllerObject.copyOrMoveBlock
  );
  nodeControllerObject._router.patch(
    `${nodeControllerObject._urlPath}/:id/makePublic`,
    [AuthRequest],
    nodeControllerObject.makeNodePublic
  );
  nodeControllerObject._router.patch(
    `${nodeControllerObject._urlPath}/:id/makePrivate`,
    [AuthRequest],
    nodeControllerObject.makeNodePrivate
  );
  nodeControllerObject._router.get(
    `${nodeControllerObject._urlPath}/public/:nodeId`,
    [],
    nodeControllerObject.getPublicNode
  );
  nodeControllerObject._router.put(
    `${nodeControllerObject._urlPath}/archive`,
    [AuthRequest],
    nodeControllerObject.archiveNode
  );
  nodeControllerObject._router.put(
    `${nodeControllerObject._urlPath}/unarchive`,
    [AuthRequest],
    nodeControllerObject.unArchiveNode
  );
  nodeControllerObject._router.post(
    `${nodeControllerObject._urlPath}/shared`,
    [AuthRequest],
    nodeControllerObject.shareNode
  );
  nodeControllerObject._router.put(
    `${nodeControllerObject._urlPath}/shared`,
    [AuthRequest],
    nodeControllerObject.updateAccessTypeForSharedNode
  );
  nodeControllerObject._router.delete(
    `${nodeControllerObject._urlPath}/shared`,
    [AuthRequest],
    nodeControllerObject.revokeNodeAccessForUsers
  );
  nodeControllerObject._router.get(
    `${nodeControllerObject._urlPath}/shared/:nodeId`,
    [AuthRequest],
    nodeControllerObject.getNodeSharedWithUser
  );
  nodeControllerObject._router.get(
    `${nodeControllerObject._urlPath}/tag/all`,
    [AuthRequest],
    nodeControllerObject.getAllTagsOfWorkspace
  );
  nodeControllerObject._router.get(
    `${nodeControllerObject._urlPath}/tag/:tagName`,
    [AuthRequest],
    nodeControllerObject.getNodeWithTag
  );
  nodeControllerObject._router.post(
    `${nodeControllerObject._urlPath}/refactor`,
    [AuthRequest],
    nodeControllerObject.refactorHierarchy
  );
  nodeControllerObject._router.post(
    `${nodeControllerObject._urlPath}/bulkCreate`,
    [AuthRequest],
    nodeControllerObject.bulkCreateNode
  );
  return;
};
