export const RouteKeys = {
  createNode: 'POST /node',
  getAllNodes: `GET /node/all/{id}`,
  getNode: 'GET /node/{id}',
  appendNode: 'POST /node/{id}/append',
  editBlock: 'POST /node/{id}/blockUpdate',
  shorten: 'POST /shorten',
  getShorts: 'GET /{namespace}/stats',
  copyOrMoveBlock: 'PATCH /node/block/movement',
  updateUserPreference: 'POST /user/update',
  createUserPreference: 'POST /user',
  getByIdAndTag: 'GET /user/{id}/{tag}',
  getByGroupIdAndTag: 'GET /user/group/{groupId}/{tag}',
  makeNodePublic: 'PATCH /node/makePublic/{id}',
  makeNodePrivate: 'PATCH /node/makePrivate/{id}',
  getPublicNode: 'GET /node/public/{id}',
  getUserByLinkedin: 'POST /user/linkedin',
  getLinkHierarchy: 'GET /workspace/hierarchy',
  getSnippet: 'GET /snippet/{id}',
  getAllVersionsOfSnippet: 'GET /snippet/{id}/all',
  createSnippet: 'POST /snippet',
  updateSnippet: 'PUT /snippet',
  createNewVersionOfExistingSnippet: 'POST /snippet/newVersion',
  makeSnippetPublic: 'PATCH /snippet/makePublic/{id}/{version}',
  makeSnippetPrivate: 'PATCH /snippet/makePrivate/{id}/{version}',
  getPublicSnippet: 'GET /snippet/public/{id}/{version}',
  clonePublicSnippet: 'POST /snippet/clone/{id}/{version}',
};
